import { useEffect, useState } from "react";
import { request, query } from "../api/client";
import { money } from "../utils/format";
export default function ShippingQuote({ city, postal, zone, street, shippingType = 'regional', weight, dimension, province, region, onPostalResolved }) {
 const [result,setResult]=useState(null);
 useEffect(()=>{let active=true;const timer=setTimeout(()=>{if(!city.trim() || (postal && !/^[0-9]{5}$/.test(postal))) return; request(`/rates/quote${query({city,postal_code:postal,zone,street,shipping_type:shippingType,weight_kg:weight,max_dimension_cm:dimension,province,region})}`).then(data=>{if(active){setResult({city,postal,zone,street,shippingType,weight,dimension,province,region,data});if(!postal && data.territory_valid && data.postal_code)onPostalResolved?.(data.postal_code);}}).catch(()=>{if(active)setResult({city,postal,zone,street,shippingType,weight,dimension,province,region,data:{available:false,reason:'Tariffa da verificare. Servizio temporaneamente non disponibile.'}});});},350);return()=>{active=false;clearTimeout(timer);};},[city,postal,zone,street,shippingType,weight,dimension,province,region,onPostalResolved]);
 const current=result?.city===city && result?.postal===postal && result?.zone===zone && result?.street===street && result?.shippingType===shippingType && result?.weight===weight && result?.dimension===dimension && result?.province===province && result?.region===region?result.data:null;
 return <div className="quote-preview" role="status"><strong>{current?.available?`Prezzo spedizione previsto: ${money(current.price_cents)}`:current?.reason || 'Inserisci comune e CAP per calcolare la tariffa.'}</strong>{current?.available && <><p>Rete EA-Express · {current.delivery_time || (current.delivery_days_min ? `${current.delivery_days_min}–${current.delivery_days_max} giorni lavorativi dal ritiro` : 'Tempi da verificare')}</p><small>{current.reason} Il rider verificherà la richiesta.</small></>}</div>;
}
